/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/index/index" |
  "/pages/assets/index" |
  "/pages/contract/index" |
  "/pages/market/index" |
  "/pages/trade/index" |
  "/subPages/feedback/index" |
  "/subPages/styles/index" |
  "/subEcharts/echarts/index" |
  "/subAsyncEcharts/asyncEcharts/index" |
  "/pagesIndex/HotContractsList" |
  "/pagesIndex/coin/detail" |
  "/pagesIndex/invite/index" |
  "/pagesIndex/notice/index" |
  "/pagesIndex/recharge/index" |
  "/pagesIndex/search/search" |
  "/pagesIndex/slider/index";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/market/index" | "/pages/trade/index" | "/pages/assets/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
